[package]
name = "neuron_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
neuron_engine = { path = ".." }
env_logger = "0.11.8"
serde = { version = "1.0.219", features = ["derive", "serde_derive", "alloc"] }
toml = "0.8.21"
serde_json = "1.0.140"
thiserror = "2.0.12"