[workspace]

[package]
name = "{name}"
edition = "2024"

[lib]
path = "scripts/script_main.rs"
crate-type = ["cdylib"]

[dependencies]
neuron_script_api = {{ git = "{api_git_repo}"{api_git_versioning} }}
