[package]
name = "neuron_runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
neuron_engine = { path = ".." }
neuron_script_api = { path = "../neuron_script_api" }
env_logger = "0.11.8"
libloading = "0.8.6"